src/Entity/Port.php
<?php

namespace App\Entity;

use App\Entity\Enums\ConnectionType;
use App\Entity\Enums\PortType;
use App\Entity\Enums\State as StateEnum;
use App\Entity\Interfaces\HarborInterface;
use App\Entity\Traits\StateTrait as StateTrait;
use App\Repository\PortRepository;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PortRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Port
{
    use StateTrait;

    const SPEED_TYPE = 'mb/s';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'Establezca el número del puerto.')]
    #[Assert\PositiveOrZero]
    private ?int $number = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'Establezca la velocidad del puerto.')]
    #[Assert\PositiveOrZero]
    private float $speed;

    #[ORM\ManyToOne(inversedBy: 'ports')]
    #[Assert\Valid]
    private ?Commutator $commutator = null;

    #[ORM\ManyToOne(inversedBy: 'ports')]
    #[Assert\Valid]
    private ?Card $card = null;

    #[ORM\OneToOne(mappedBy: 'port', targetEntity: Equipment::class, cascade: ['persist', 'remove'])]
    #[Assert\Valid]
    private ?Equipment $equipment = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $connectionType = null;

    #[Assert\Choice(
        choices: [
            ConnectionType::Direct,
            ConnectionType::Full,
            ConnectionType::Simple,
            ConnectionType::SlaveModem,
            ConnectionType::SlaveSwitch],
        message: 'Seleccione un tipo de conexion válido.'
    )]
    private ?ConnectionType $enumConnectionType = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $portType = null;

    #[Assert\Choice(
        choices: [PortType::Optic, PortType::Electric],
        message: 'Seleccione un tipo de puerto válido.'
    )]
    private ?PortType $enumPortType = null;

    public function __construct(?int $number = null, ?ConnectionType $connectionType = null)
    {
        $this->number = $number;
        $this->speed = 1;
        $this->enumState = StateEnum::Active;
        $this->enumPortType = PortType::Electric;
        if(!is_null($connectionType)){
            $this->enumConnectionType = $connectionType;
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): int
    {
        return $this->number;
    }

    /*public function setNumber(string $number): static
    {
        $this->number = $number;

        return $this;
    }*/

    public function getSpeed(): float
    {
        return $this->speed;
    }

    /*public function setSpeed(float $speed): static
    {
        $this->speed = $speed;

        return $this;
    }*/

    public function getCommutator(): ?Commutator
    {
        return $this->commutator;
    }

    public function setCommutator(?Commutator $commutator): static
    {
        $this->commutator = $commutator;

        return $this;
    }

    public function getCard(): ?Card
    {
        return $this->card;
    }

    public function setCard(?Card $card): static
    {
        $this->card = $card;

        return $this;
    }

    public function isFromCommutator(): bool
    {
        return !is_null($this->getCommutator());
    }

    public function isFromCard(): bool
    {
        return !is_null($this->getCard());
    }

    public function getEquipment(): ?Equipment
    {
        return $this->equipment;
    }

    /**
     * @throws Exception
     */
    public function setEquipment(?Equipment $equipment): static
    {
        if(!$equipment instanceof Modem && $this->isFromCard()){
            throw new Exception('Only modems can be connected directly to the card ports.');
        }

        $this->equipment = $equipment;

        return $this;
    }

    /**
     * @throws Exception
     */
    public function connectCamera(Camera $camera): static
    {
        return $this->setEquipment($camera);
    }

    /**
     * @throws Exception
     */
    public function connectMsam(Msam $msam): static
    {
        return $this->setEquipment($msam);
    }

    /**
     * @throws Exception
     */
    public function connectModem(Modem $modem): static
    {
        return $this->setEquipment($modem);
    }

    /**
     * @throws Exception
     */
    public function connectServer(Server $server): static
    {
        return $this->setEquipment($server);
    }

    /**
     * @throws Exception
     */
    public function connectCommutator(Commutator $commutator): static
    {
        return $this->setEquipment($commutator);
    }

    public function hasConnectedCamera(): bool
    {
        return $this->getEquipment() instanceof Camera;
    }

    public function hasConnectedMsam(): bool
    {
        return $this->getEquipment() instanceof Msam;
    }

    public function hasConnectedModem(): bool
    {
        return $this->getEquipment() instanceof Modem;
    }

    public function hasConnectedServer(): bool
    {
        return $this->getEquipment() instanceof Server;
    }

    public function hasConnectedCommutator(): bool
    {
        return $this->getEquipment() instanceof Commutator;
    }

    public function configure(float $speed, ?PortType $type = null): static
    {
        $this->speed = $speed;
        if(!is_null($type)){
            $this->setPortType($type);
        }

        return $this;
    }

    /**
     * @param Port|null $port puerto al cual se pasara el equipo conectado a este
     * @return Port
     * @throws Exception
     */
    public function disabled(?Port $port): static
    {
        if (!is_null($this->equipment) && is_null($port)) {
            throw new Exception('This port must be disabled, but the equipment connected to it must be placed in another free port.');
        }

        //este puerto se desabilita
        $this->setState(StateEnum::Inactive);

        if (!is_null($this->getEquipment())) {
            //si el puerto tiene conectado algun equipo, ese equipo debe pasarce a otro puerto libre
            $port->setEquipment($this->getEquipment());
            //TODO: debo quitar el equipo de este puerto
            $this->setEquipment(null);
        }

        return $this;
    }

    /**
     * Si no tiene nada conectado el puerto esta libre
     * @return bool
     */
    public function isFree(): bool
    {
        return is_null($this->getEquipment());
    }

    /**
     * @param HarborInterface|null $harbor
     * @return $this
     */
    public function setHarbor(?HarborInterface $harbor): static
    {
        if($harbor instanceof Card){
            $this->setCard($harbor);
            return $this;
        }

        if($harbor instanceof Commutator){
            $this->setCommutator($harbor);
            return $this;
        }

        $this->setCard(null);
        $this->setCommutator(null);
        return $this;
    }

    /**
     * @return HarborInterface|null
     */
    public function getHarbor(): ?HarborInterface
    {
        if($this->isFromCard()){
            return $this->getCard();
        }

        if($this->isFromCommutator()){
            return $this->getCommutator();
        }

        return null;
    }

    public function getConnectionType(): ?ConnectionType
    {
        return $this->enumConnectionType;
    }

    /**
     * @throws Exception
     */
    public function setConnectionType(ConnectionType $connectionType): static
    {
        if(!$this->isFromCommutator()){
            throw new Exception('Solo los puertos de switch pueden tener el tipo de conexión.');
        }
        $this->connectionType = "0";
        $this->enumConnectionType = $connectionType;

        return $this;
    }

    public function getPortType(): ?PortType
    {
        return $this->enumPortType;
    }

    /**
     * @throws Exception
     */
    public function setPortType(PortType $portType): static
    {
        $this->portType = "";
        $this->enumPortType = $portType;

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function onSave(): void
    {
        $this->state = $this->getState()->value;
        $this->portType = $this->getPortType()->value;
        if(!is_null($this->enumConnectionType)){
            if($this->enumConnectionType === ConnectionType::Null){
                $this->connectionType = null;
            }else{
                $this->connectionType = $this->getConnectionType()->value;
            }
        }
    }

    /**
     * @throws Exception
     */
    #[ORM\PostLoad]
    public function onLoad(): void
    {
        $this->setState(StateEnum::from($this->state));
        $this->setPortType(PortType::from($this->portType));
        if(!is_null($this->connectionType)){
            $this->setConnectionType(ConnectionType::from($this->connectionType));
        }
    }

    /**
     * Deactivate
     * @return $this
     */
    public function deactivate(): static
    {
        $this->getEquipment()?->deactivate();
        $this->state = null;
        $this->setState(StateEnum::Inactive);

        return $this;
    }

    public function getTypeValue():string
    {
        return PortType::getValueFrom($this->getPortType());
    }

    public function getTypeLabel():string
    {
        return PortType::getLabelFrom($this->getPortType());
    }

}

src/Form/CardType.php
<?php

namespace App\Form;

use App\Entity\Card;
use App\Entity\Msam;
use App\Repository\MsamRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CardType extends AbstractType
{
    public function __construct(private readonly MsamRepository $msamRepository)
    {}

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $msam = ($options['msam'] instanceof Msam) ? $options['msam'] : $this->msamRepository->find($options['msam']);
        $position = $msam->connectedCards() + 1;

        $builder->add('name', null, [
            'label' => 'Nombre:'
        ]);

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($position): void {
            $msam = $event->getData();
            $form = $event->getForm();

            if (!$msam || null === $msam->getId()) {
                $form->add('slot', HiddenType::class, [
                    'data' => $position
                ]);

                $form->add('portsAmount', null, [
                    'attr' => [
                        'min' => 1,
                        'max' => 16,
                        'list' => 'ports_amount'
                    ],
                    'data' => 1
                ]);
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Card::class,
            'attr' => [
                'novalidate' => true,
                'class' => 'msam_card'
            ],
            'msam' => null,
        ]);

        $resolver->setAllowedTypes('msam', 'int');
    }
}

src/Controller/CardController.php
<?php

namespace App\Controller;

use App\Entity\Card;
use App\Entity\Enums\PortType;
use App\Entity\Msam;
use App\Form\CardType;
use App\Repository\CardRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/card')]
class CardController extends AbstractController
{
    #[Route('/msam/{msam}', name: 'card_index', requirements: ['msam' => '\d+'], methods: ['GET'])]
    public function index(Request $request, CardRepository $cardRepository, Msam $msam): Response
    {
        $template = ($request->isXmlHttpRequest()) ? '_manage.html.twig' : 'index.html.twig';

        return $this->render("card/$template", [
            'cards' => $cardRepository->findBy(['msam' => $msam]),
            'msam' => $msam,
            'paginator' => null
        ]);
    }

    #[Route('/new/msam/{msam}', name: 'card_new', requirements: ['msam' => '\d+'], methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, Msam $msam): Response
    {
        $card = new Card();
        $form = $this->createForm(CardType::class, $card, [
            'action' => $this->generateUrl('card_new', ['msam' => $msam->getId()]),
            'msam' => $msam->getId()
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $card->setMsam($msam);
            $entityManager->persist($card);
            $entityManager->flush();

            //si el formulario se mando correctamente por ajax
            if($request->isXmlHttpRequest()){
                return $this->render("partials/_form_success.html.twig", [
                    'id' => 'new_card_'.$card->getId(),
                    'type' => 'text-bg-success',
                    'message' => 'Se ha agregado una targeta al msam.'
                ]);
            }

            $this->addFlash('success', 'Se ha agregado una targeta al msam.');
            return $this->redirectToRoute('card_index', ['msam' => $msam->getId()], Response::HTTP_SEE_OTHER);
        }

        $template = ($request->isXmlHttpRequest()) ? '_form.html.twig' : 'new.html.twig';

        return $this->render("card/$template", [
            'card' => $card,
            'form' => $form,
            'msam' => $msam,
            'title' => 'Nueva targeta'
        ]);
    }

    #[Route('/{id}/edit/msam/{msam}', name: 'card_edit', requirements: ['id' => '\d+', 'msam' => '\d+'], methods: ['GET', 'POST'])]
    public function edit(Request $request, Card $card, EntityManagerInterface $entityManager, Msam $msam): Response
    {
        $form = $this->createForm(CardType::class, $card, [
            'action' => $this->generateUrl('card_edit', ['id' => $card->getId(), 'msam' => $msam->getId()]),
            'msam' => $msam->getId()
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            //si el formulario se mando correctamente por ajax
            if($request->isXmlHttpRequest()){
                return $this->render("partials/_form_success.html.twig", [
                    'id' => 'edit_card_'.$card->getId(),
                    'type' => 'text-bg-success',
                    'message' => 'Se ha modificado la targeta del msam.'
                ]);
            }

            $this->addFlash('success', 'Se ha modificado la targeta del msam.');
            return $this->redirectToRoute('card_index', ['msam' => $msam->getId()], Response::HTTP_SEE_OTHER);
        }

        $template = ($request->isXmlHttpRequest()) ? '_form.html.twig' : 'edit.html.twig';

        return $this->render("card/$template", [
            'card' => $card,
            'form' => $form,
            'msam' => $msam,
            'title' => 'Editar targeta'
        ]);
    }

    #[Route('/port/{id}', name: 'card_port', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function port(Request $request, Card $card): Response
    {
        $template = ($request->isXmlHttpRequest()) ? '_port_detail.html.twig' : 'port.html.twig';

        return $this->render("card/$template", [
            'card' => $card,
            'title' => 'Puertos de la targeta',
            'forSelect' => PortType::forSelect(),
        ]);
    }
}

templates/card/_delete_form.html.twig
<form method="post" action="" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ card.id) }}">
    <button class="btn">Delete</button>
</form>

templates/card/_form.html.twig
{% embed "embeds/card.html.twig" %}
    {% block card_css_class %}mb-4{% endblock %}

    {% block card_header_css_class %}d-flex justify-content-between align-items-center{% endblock %}

    {% block card_title %}{{ title }}{% endblock %}

    {% block card_header_options %}
        <div>
            {% if showButton is defined and showButton == true%}
                <a class="btn btn-primary btn-sm active" href="{{ path('card_index', {'msam':msam.id}) }}">
                    <i class="fas fa-arrow-left"></i>
                    Listado de targetas
                </a>
            {% endif %}
        </div>
    {% endblock %}

    {% block card_body %}
        {% form_theme form 'form/bootstrap_5_horizontal_layout_sm.html.twig' %}

        {{ form_start(form) }}
        {{ include('card/_form_fields.html.twig') }}

        <div class="row mb-3">
            <div class="col-sm-10 offset-sm-2">
                <button class="btn btn-success">
                    <i class="fas fa-save"></i>
                    Guardar
                </button>
            </div>
        </div>
        {{ form_end(form) }}
    {% endblock %}

    {% block card_footer %}
        {% if showButton is defined and showButton == true%}
            <div class="card-footer text-body-secondary">
                <a href="{{ path('card_index', {'msam':msam.id}) }}" class="btn btn-primary">
                    <i class="fas fa-arrow-left"></i>
                    Listado de targetas
                </a>
            </div>
        {% endif %}
    {% endblock %}
{% endembed %}

templates/card/_form_fields.html.twig
{{ form_row(form.name) }}
{% if form.slot is defined %}
    {{ form_row(form.slot) }}
{% endif %}
{% if form.portsAmount is defined %}
    {{ form_row(form.portsAmount) }}
{% endif %}

templates/card/_list.html.twig
{% embed "embeds/card.html.twig" %}
    {% block card_css_class %}mb-4{% endblock %}

    {% block card_header_css_class %}d-flex justify-content-between align-items-center{% endblock %}

    {% block card_title %}Targetas del msam: {{ msam }}{% endblock %}

    {% block card_header_options %}
        {% if msam.canAddTarget() %}
            <div>
                <a class="btn btn-primary btn-sm active"
                   data-action="page#showFormContent"
                   href="{{ path('card_new', {'msam':msam.id}) }}"
                >
                    <i class="fas fa-plus"></i>
                    Nueva targeta
                </a>
            </div>
        {% endif %}
    {% endblock %}

    {% block card_body %}
        {% embed "embeds/table.html.twig" %}
            {% block table_container %}
                {# se puede poner el data-action #}
            {% endblock %}

            {% block table_head %}
                <tr>
                    <th>Nombre</th>
                    <th>Slot</th>
                    <th>Cantidad de puertos</th>
                    <th></th>
                </tr>
            {% endblock %}

            {% block table_body %}
                {% for card in cards %}
                    <tr>
                        <td>{{ card.name }}</td>
                        <td>{{ card.slot }}</td>
                        <td>{{ card.portsAmount }}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" title="Editar targeta"
                               href="{{ path('card_edit', {'id': card.id, 'msam': msam.id}) }}"
                               data-action="page#showFormContent"
                            >
                                <i class="fas fa-edit"></i>
                            </a>
                            <a class="btn btn-sm btn-primary position-relative" title="Puertos de la targeta"
                               href="{{ path('card_port', {'id':card.id}) }}"
                               data-action="page#showFormContent"
                            >
                                <i class="fas fa-server"></i>
                                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                                    {{ card.portsAmount }}
                                    <span class="visually-hidden">cantidad de puertos</span>
                              </span>
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="13">No se encontraron targetas</td>
                    </tr>
                {% endfor %}
            {% endblock %}
        {% endembed %}

    {% endblock %}
{% endembed %}

templates/card/_manage.html.twig
{{ include('partials/_index_container.html.twig', {
    list: 'card/_list.html.twig',
    rest_data_action: 'page:onChangeState->content-loader#refreshContent',
    list_container_url: path('card_index', {'msam':msam.id})
}) }}

templates/card/_port_detail.html.twig
{% embed "embeds/card.html.twig" %}
    {% block card_css_class %}mb-4{% endblock %}

    {% block card_extra %}{% endblock %}

    {% block card_header_css_class %}d-flex justify-content-between align-items-center{% endblock %}

    {% block card_title %}{{ title }}{% endblock %}

    {% block card_header_options %}{% endblock %}

    {% block card_body %}
        <div class="row" style="position: relative">
            {% for port in card.ports %}
                <div class="col-3 mb-4" {{ stimulus_controller('port', {
                    stateHref: path('port_state'),
                    speedHref: path('port_speed'),
                    listHref: path('card_port', {'id':card.id}),
                    typeHref: path('port_type'),
                }) }}
                     data-action="port:onChangeState->content-loader#refreshContent">
                    <div class="card text-white bg-gradient-secondary">
                        <div class="card-body" style="padding: 0.5rem">
                            <div class="row align-items-center no-gutters">
                                <div class="col-auto">
                                    <i class="fas {% if port.equipment %}fa-check-circle{% else %}fa-circle{% endif %} fa-2x text-gray-300"></i>
                                    {% if port.state %}<span>{% endif %}
                                    <div class="form-check form-switch">
                                        <input
                                                class="form-check-input"
                                                type="checkbox"
                                                role="switch"
                                                {% if port.isActive() %}checked{% endif %}
                                                data-action="change->port#state:prevent"
                                                data-port-id-param="{{ port.id }}"
                                                {% if port.isActive() %}
                                                    data-port-state-param="0"
                                                {% else %}
                                                    data-port-state-param="1"
                                                {% endif %}
                                        >
                                    </div>
                                    {% if port.state %}</span>{% endif %}
                                </div>
                                <div class="col me-2">
                                    <div class="text-uppercase text-white fw-bold text-xs mb-1">
                                        <input
                                                type="text"
                                                value="{{ port.speed }}"
                                                class="w-25"
                                                data-action="blur->port#speed"
                                                data-port-id-param="{{ port.id }}"
                                        >
                                        <span>{{ constant('App\\Entity\\Port::SPEED_TYPE') }} -</span>
                                        <br>
                                        <span class="">
                                            {{ port.equipment }}
                                        </span>
                                    </div>
                                    <h5 class="card-title">Puerto: <span class="fw-bold">{{ port.number }}</span></h5>
                                    <select style="font-size: 11.5px"
                                            data-action="change->port#type"
                                            data-port-id-param="{{ port.id }}"
                                    >
                                        {% for label, value in forSelect %}
                                            {% if value is not same as "" %}
                                                <option value="{{ value }}" {% if port.typeValue == value %}selected{% endif %}>
                                                    {{ label }}
                                                </option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endblock %}

    {% block card_footer %}
        {% if showButton is defined and showButton == true %}
            <div class="card-footer text-body-secondary">
                <div class="row">
                    <div class="col-6">
                        <a href="" class="btn btn-primary">
                            <i class="fas fa-arrow-left"></i>
                            Listado de Switchs
                        </a>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endblock %}
{% endembed %}

templates/card/edit.html.twig
{% extends 'content.html.twig' %}

{% block title %}Editar Targeta{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8">
            <h3 class="text-dark mb-4">Editar targeta</h3>
        </div>
        {{ component('Breadcrumb', {
            options: [
                {label: 'Inicio', href: path('app_home')},
                {label: 'Targetas', href: path('card_index', {'msam':msam.id})},
                {label: 'Editar'},
            ],
            current: 'Editar'
        }) }}
    </div>

    {{ include('card/_form.html.twig', {'showButton': true, 'title': title}) }}
{% endblock %}

templates/card/index.html.twig
{% extends 'content.html.twig' %}

{% block title %}Gestionar targetas del msam: {{ msam }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8">
            <h3 class="text-dark mb-4">Gestionar targetas del msam: <a href="{{ path('msam_show', {'id':msam.id}) }}">{{ msam }}</a></h3>
        </div>

        {{ component('Breadcrumb', {
            options: [
                {label: 'Inicio', href: path('app_home')},
                {label: 'Targetas de Msam', href: path('card_index', {'msam':msam.id})},
                {label: 'Lista'},
            ],
            current: 'Lista'
        }) }}
    </div>

    {{ include('partials/_index_container.html.twig', {
        list: 'card/_list.html.twig',
        rest_data_action: 'page:onChangeState->content-loader#refreshContent'
    }) }}
{% endblock %}

templates/card/new.html.twig
{% extends 'content.html.twig' %}

{% block title %}Nueva targeta{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8">
            <h3 class="text-dark mb-4">Crear nueva targeta</h3>
        </div>
        {{ component('Breadcrumb', {
            options: [
                {label: 'Inicio', href: path('app_home')},
                {label: 'Targetas', href: path('card_index', {'msam':msam.id})},
                {label: 'Nuevo'},
            ],
            current: 'Nuevo'
        }) }}
    </div>

    {{ include('card/_form.html.twig', {'showButton': true, 'title': title}) }}
{% endblock %}

templates/card/port.html.twig
{% extends 'content.html.twig' %}

{% block title %}Commutator{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8">
            <h3 class="text-dark mb-4">Puertos del switch</h3>
        </div>
        {{ component('Breadcrumb', {
            options: [
                {label: 'Inicio', href: path('app_home')},
                {label: 'Switch', href: path('commutator_index')},
                {label: 'Puertos'},
            ],
            current: 'Detalle'
        }) }}
    </div>

    {{ include('commutator/_port_detail.html.twig', {'title': 'Puertos', 'showButton': true}) }}

{% endblock %}

templates/card/show.html.twig
{% extends 'content.html.twig' %}

{% block title %}Targeta{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8">
            <h3 class="text-dark mb-4">Datos de la targeta</h3>
        </div>
        {{ component('Breadcrumb', {
            options: [
                {label: 'Inicio', href: path('app_home')},
                {label: 'Targetas', href: path('card_index', {'msam':msam.id})},
                {label: 'Detalle'},
            ],
            current: 'Detalle'
        }) }}
    </div>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ card.id }}</td>
            </tr>
            <tr>
                <th>Slot</th>
                <td>{{ card.slot }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ card.name }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}