src/Entity/Report.php
<?php

namespace App\Entity;

use App\Entity\Enums\Aim;
use App\Entity\Enums\Flaw;
use App\Entity\Enums\InterruptionReason;
use App\Entity\Enums\Priority;
use App\Entity\Enums\ReportState;
use App\Entity\Enums\ReportType;
use App\Repository\ReportRepository;
use DateTime;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ReportRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Report
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $number = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'El reporte debe de tener una especialidad.')]
    private string $specialty = 'videoproteccion';

    #[ORM\Column]
    private ?DateTimeImmutable $entryDate = null;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $closeDate = null;

    #[ORM\Column(length: 255)]
    private string $type;

    #[Assert\Choice(
        choices: [ReportType::Camera, ReportType::Server, ReportType::Msam, ReportType::Modem, ReportType::Switch],
        message: 'Seleccione un tipo de reporte válido.'
    )]
    private ReportType $enumType;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $interruptionReason = null;

    #[ORM\Column(length: 255)]
    private string $priority;

    #[Assert\Choice(
        choices: [Priority::Hight, Priority::Medium, Priority::Low],
        message: 'Seleccione una prioridad válida.'
    )]
    private Priority $enumPriority;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Valid]
    private ?Equipment $equipment = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $flaw = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $observation = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $solution = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'El reporte debe de tener una unidad.')]
    private string $unit = 'Unidad 1';

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Valid]
    private ?User $boss = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Valid]
    private ?User $managementOfficer = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    #[Assert\Valid]
    private ?User $technical = null;

    #[ORM\Column(length: 255)]
    private string $state;

    #[Assert\Choice(choices: [ReportState::Open, ReportState::Close], message: 'Seleccione un estado válido.')]
    private ReportState $enumState;

    #[ORM\Column(length: 255)]
    private string $aim;

    #[Assert\Choice(choices: [Aim::Via, Aim::Objective, Aim::Border, Aim::Confrontation, Aim::Tuition], message: 'Seleccione una función válida.')]
    private Aim $enumAim;

    #[ORM\ManyToOne]
    #[Assert\Valid]
    private ?Organ $organ = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $detail = null;

    public function __construct()
    {
//        $this->entryDate = new \DateTime();
//        $this->number = $this->entryDate->getTimestamp().'-'.$this->equipment->getShortName();
        $this->enumPriority = Priority::Hight;
        $this->enumState = ReportState::Open;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): string
    {
        return $this->number;
    }

    public function setNumber(string $number): static
    {
        $this->number = $number;

        return $this;
    }

    public function getSpecialty(): string
    {
        return str_replace('_', ' ', $this->specialty);
    }

    /*public function setSpecialty(string $specialty): static
    {
        $this->specialty = $specialty;

        return $this;
    }*/

    public function getEntryDate(): ?DateTimeImmutable
    {
        return $this->entryDate;
    }

    public function setEntryDate(DateTimeImmutable $entryDate): static
    {
        $this->entryDate = $entryDate;

        return $this;
    }

    public function getCloseDate(): ?DateTimeImmutable
    {
        return $this->closeDate;
    }

    public function setCloseDate(?DateTimeImmutable $closeDate): static
    {
        $this->closeDate = $closeDate;

        return $this;
    }

    public function getType(): ReportType
    {
        return $this->enumType;
    }

    public function setType(ReportType $type): static
    {
        $this->enumType = $type;

        return $this;
    }

    public function getInterruptionReason(): ?string
    {
        return $this->interruptionReason;
    }

    public function setInterruptionReason(InterruptionReason|string|null $interruptionReason): static
    {
        /*if(is_string($interruptionReason)){
            $this->interruptionReason = $interruptionReason;
        }else{
            $this->interruptionReason = $interruptionReason->value;
        }*/

        $this->interruptionReason = (is_string($interruptionReason)) ? $interruptionReason : $interruptionReason->value;

        return $this;
    }

    public function getPriority(): Priority
    {
        return $this->enumPriority;
    }

    public function setPriority(Priority $priority): static
    {
        $this->enumPriority = $priority;

        return $this;
    }

    public function getEquipment(): ?Equipment
    {
        return $this->equipment;
    }

    public function setEquipment(Equipment $equipment): static
    {
        $this->equipment = $equipment;

        return $this;
    }

    public function getFlaw(): ?string
    {
        return $this->flaw;
    }

    public function setFlaw(Flaw|string|null $flaw): static
    {
        /*if(is_string($flaw)){
            $this->flaw = $flaw;
        }else{
            $this->flaw = $flaw->value;
        }*/
        $this->flaw = (is_string($flaw)) ? $flaw : $flaw->value;

        return $this;
    }

    public function getObservation(): ?string
    {
        return $this->observation;
    }

    public function setObservation(?string $observation): static
    {
        $this->observation = $observation;

        return $this;
    }

    public function getSolution(): ?string
    {
        return $this->solution;
    }

    public function setSolution(?string $solution): static
    {
        $this->solution = $solution;

        return $this;
    }

    public function getUnit(): string
    {
        return $this->unit;
    }

    public function setUnit(string $unit): static
    {
        $this->unit = $unit;

        return $this;
    }

    public function getBoss(): ?User
    {
        return $this->boss;
    }

    public function setBoss(?User $boss): static
    {
        $this->boss = $boss;

        return $this;
    }

    public function getManagementOfficer(): ?User
    {
        return $this->managementOfficer;
    }

    public function setManagementOfficer(?User $managementOfficer): static
    {
        $this->managementOfficer = $managementOfficer;

        return $this;
    }

    public function getState(): ReportState
    {
        return $this->enumState;
    }

    public function setState(ReportState $state): static
    {
        $this->enumState = $state;

        return $this;
    }

    public function getAim(): Aim
    {
        return $this->enumAim;
    }

    public function setAim(Aim $aim): static
    {
        $this->enumAim = $aim;

        return $this;
    }

    public function getOrgan(): ?Organ
    {
        return $this->organ;
    }

    public function setOrgan(?Organ $organ): static
    {
        $this->organ = $organ;

        return $this;
    }

    public function getPhysicalAddress(): string
    {
        return $this->getEquipment()->getPhysicalAddress();
    }

    public function getMunicipality(): Municipality
    {
        return $this->getEquipment()->getMunicipality();
    }

    #[ORM\PrePersist]
    public function beforeSave(): void
    {
        $this->entryDate = new DateTimeImmutable();
        $this->number = $this->entryDate->getTimestamp().'-'.$this->equipment->getShortName();
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function onSave(): void
    {
        $this->type = $this->getType()->value;
        $this->priority = $this->getPriority()->value;
        $this->state = $this->getState()->value;
        $this->aim = $this->getAim()->value;
    }

    #[ORM\PostLoad]
    public function onLoad(): void
    {
        $this->setType(ReportType::from($this->type));
        $this->setPriority(Priority::from($this->priority));
        $this->setState(ReportState::from($this->state));
        $this->setAim(Aim::from($this->aim));
    }

    public function close(): void
    {
        if($this->getSolution()){
            $this->closeDate = new DateTimeImmutable('now');
            $this->setState(ReportState::Close);
        }
    }

    public function isOpen(): bool
    {
        return $this->enumState->value === ReportState::Open->value;
    }

    public function getTechnical(): ?User
    {
        return $this->technical;
    }

    public function setTechnical(?User $technical): static
    {
        $this->technical = $technical;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

}

src/Controller/StructuredCableController.php
<?php

namespace App\Controller;

use App\Entity\Camera;
use App\Entity\Modem;
use App\Entity\StructuredCable;
use App\Form\StructuredCableType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/structured/cable')]
class StructuredCableController extends AbstractController
{
    #[Route('/new_in_camera/{camera}', name: 'structured_cable_new_camera', requirements: ['camera' => '\d+'], methods: ['GET', 'POST'])]
    public function newCableInCamera(Request $request, EntityManagerInterface $entityManager, Camera $camera): Response
    {
        $template = ($request->isXmlHttpRequest()) ? '_form_camera.html.twig' : 'new.html.twig';
        return $this->newCable(
            $request,
            $entityManager,
            $camera,
            'structured_cable_new_camera',
            ['camera' => $camera->getId()],
            'camera_index',
            $template
        );
    }

    #[Route('edit_in_camera/{id}/edit/{camera}', name: 'structured_cable_edit_camera', requirements: ['id' => '\d+', 'camera' => '\d+'], methods: ['GET', 'POST'])]
    public function editCableInCamera(Request $request, StructuredCable $structuredCable, EntityManagerInterface $entityManager, Camera $camera): Response
    {
        $template = ($request->isXmlHttpRequest()) ? '_form_camera.html.twig' : 'edit.html.twig';
        return $this->editCable($request, $structuredCable, $entityManager, $camera, 'structured_cable_edit_camera', ['id' => $structuredCable->getId(), 'camera' => $camera->getId()], 'camera_index', $template);
    }

    #[Route('delete_in_camera/{id}/{camera}', name: 'structured_cable_delete_camera', requirements: ['id' => '\d+', 'camera' => '\d+'], methods: ['POST'])]
    public function deleteCableInCamera(Request $request, StructuredCable $structuredCable, EntityManagerInterface $entityManager, Camera $camera): Response
    {
        return $this->deleteCable($request, $structuredCable, $entityManager, $camera);
    }

    #[Route('/new_in_modem/{modem}', name: 'structured_cable_new_modem', requirements: ['modem' => '\d+'], methods: ['GET', 'POST'])]
    public function newCableInModem(Request $request, EntityManagerInterface $entityManager, Modem $modem): Response
    {
        $template = ($request->isXmlHttpRequest()) ? '_form_modem.html.twig' : 'new.html.twig';
        return $this->newCable(
            $request,
            $entityManager,
            $modem,
            'structured_cable_new_modem',
            ['modem' => $modem->getId()],
            'modem_index',
            $template
        );
    }

    #[Route('edit_in_modem/{id}/edit/{modem}', name: 'structured_cable_edit_modem', requirements: ['id' => '\d+', 'modem' => '\d+'], methods: ['GET', 'POST'])]
    public function editCableInModem(Request $request, StructuredCable $structuredCable, EntityManagerInterface $entityManager, Modem $modem): Response
    {
        $template = ($request->isXmlHttpRequest()) ? '_form_modem.html.twig' : 'edit.html.twig';
        return $this->editCable($request, $structuredCable, $entityManager, $modem, 'structured_cable_edit_modem', ['id' => $structuredCable->getId(), 'modem' => $modem->getId()], 'camera_index', $template);
    }

    #[Route('delete_in_modem/{id}/{camera}', name: 'structured_cable_delete_modem', requirements: ['id' => '\d+', 'camera' => '\d+'], methods: ['POST'])]
    public function deleteCableInModem(Request $request, StructuredCable $structuredCable, EntityManagerInterface $entityManager, Modem $modem): Response
    {
        return $this->deleteCable($request, $structuredCable, $entityManager, $modem);
    }

    private function deleteCable(Request $request, StructuredCable $structuredCable, EntityManagerInterface $entityManager, $entity): Response
    {
        if ($this->isCsrfTokenValid('delete'.$structuredCable->getId(), $request->request->get('_token'))) {
            try{
                $entity->setStructuredCable(null);
                $entityManager->remove($structuredCable);
                $entityManager->flush();

                return $this->render("partials/_form_success.html.twig", [
                    'id' => 'delete_structured_cable',
                    'type' => 'text-bg-success',
                    'message' => 'Se ha eliminado el cable estructurado.'
                ]);
            }catch (\Exception $exception){
                return $this->render("partials/_form_success.html.twig", [
                    'id' => 'delete_structured_cable',
                    'type' => 'text-bg-danger',
                    'message' => $exception->getMessage()
                ]);
            }
        }

        throw new BadRequestHttpException('Ajax request');
    }

    private function newCable(Request $request, EntityManagerInterface $entityManager, $entity, $formPath, $formPathParams, $pathIndex, $template): Response
    {
        $structuredCable = new StructuredCable();
        $form = $this->createForm(StructuredCableType::class, $structuredCable, [
            'action' => $this->generateUrl($formPath, $formPathParams),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try{
                $entity->setStructuredCable($structuredCable);
                $entityManager->persist($structuredCable);
                $entityManager->flush();

                //si el formulario se mando correctamente por ajax
                if($request->isXmlHttpRequest()){
                    return $this->render("partials/_form_success.html.twig", [
                        'id' => 'new_structured_cable_'.$structuredCable->getId(),
                        'type' => 'text-bg-success',
                        'message' => 'Se ha modificado el cable estructurado.'
                    ]);
                }
            }catch (\Exception $exception){
                if($request->isXmlHttpRequest()){
                    return $this->render("partials/_form_success.html.twig", [
                        'id' => 'new_structured_cable_'.$structuredCable->getId(),
                        'type' => 'text-bg-danger',
                        'message' => $exception->getMessage()
                    ]);
                }
            }

            $this->addFlash('success', 'Se ha modificado el cable estructurado.');
            return $this->redirectToRoute($pathIndex, [], Response::HTTP_SEE_OTHER);
        }

        return $this->render("structured_cable/$template", [
            'structured_cable' => $structuredCable,
            'form' => $form,
            'title' => 'Modificar cable estructurado',
        ]);
    }

    public function editCable(Request $request, StructuredCable $structuredCable, EntityManagerInterface $entityManager, $entity, $formPath, $formPathParams, $pathIndex, $template): Response
    {
        $form = $this->createForm(StructuredCableType::class, $structuredCable, [
            'action' => $this->generateUrl($formPath, $formPathParams),
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            //si el formulario se mando correctamente por ajax
            if($request->isXmlHttpRequest()){
                return $this->render("partials/_form_success.html.twig", [
                    'id' => 'edit_structured_cable_'.$structuredCable->getId(),
                    'type' => 'text-bg-success',
                    'message' => 'Se ha modificado el cable estructurado.'
                ]);
            }

            $this->addFlash('success', 'Se ha modificado el cable estructurado.');

            return $this->redirectToRoute($pathIndex, [], Response::HTTP_SEE_OTHER);
        }

        return $this->render("structured_cable/$template", [
            'structured_cable' => $structuredCable,
            'form' => $form,
            'title' => 'Modificar cable estructurado',
            'entity' => $entity
        ]);
    }

}

templates/structured_cable/_delete_form.html.twig
<form
        method="post"
        action="{{ path('structured_cable_delete_camera', {'id': structured_cable.id, 'camera': camera.id}) }}"
        onsubmit="return confirm('Está seguro que desea eliminar este cable estructurado?');"
>
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ structured_cable.id) }}">
    <button class="btn btn-primary btn-sm active">
        <i class="fas fa-trash"></i>
        Eliminar cable estructurado
    </button>
</form>

templates/structured_cable/_form.html.twig
{% embed "embeds/card.html.twig" %}
    {% block card_css_class %}mb-4{% endblock %}

    {% block card_header_css_class %}d-flex justify-content-between align-items-center{% endblock %}

    {% block card_title %}{{ title }}{% endblock %}

    {% block card_header_options %}
        <div>
            {% if showButton is defined and showButton == true%}
                <a class="btn btn-primary btn-sm active" href="{{ path('camera_index') }}">
                    <i class="fas fa-arrow-left"></i>
                    Listado
                </a>
            {% endif %}

            {% if camera is defined %}
                {{ include('structured_cable/_delete_form.html.twig', {'camera': camera}) }}
            {% endif %}
        </div>
    {% endblock %}

    {% block card_body %}
        {% form_theme form 'form/bootstrap_5_horizontal_layout_sm.html.twig' %}

        {{ form_start(form) }}
            {{ form_widget(form) }}
        <div class="row mb-3">
            <div class="col-sm-10 offset-sm-2">
                <button class="btn btn-success">
                    <i class="fas fa-save"></i>
                    Guardar
                </button>
            </div>
        </div>
        {{ form_end(form) }}
    {% endblock %}

    {% block card_footer %}
        {% if showButton is defined and showButton == true%}
            <div class="card-footer text-body-secondary">
                <a href="{{ path('camera_index') }}" class="btn btn-primary">
                    <i class="fas fa-arrow-left"></i>
                    Listado
                </a>
            </div>
        {% endif %}
    {% endblock %}
{% endembed %}

templates/structured_cable/_form_camera.html.twig
{% embed "embeds/card.html.twig" %}
    {% block card_css_class %}mb-4{% endblock %}

    {% block card_header_css_class %}d-flex justify-content-between align-items-center{% endblock %}

    {% block card_title %}{{ title }}{% endblock %}

    {% block card_header_options %}
        <div>
            {% if showButton is defined and showButton == true%}
                <a class="btn btn-primary btn-sm active" href="{{ path('camera_index') }}">
                    <i class="fas fa-arrow-left"></i>
                    Listado
                </a>
            {% endif %}

            {% if camera is defined %}
                {{ include('structured_cable/_delete_form.html.twig', {'camera': camera}) }}
            {% endif %}
        </div>
    {% endblock %}

    {% block card_body %}
        {% form_theme form 'form/bootstrap_5_horizontal_layout_sm.html.twig' %}

        {{ form_start(form) }}
            {{ form_widget(form) }}
        <div class="row mb-3">
            <div class="col-sm-10 offset-sm-2">
                <button class="btn btn-success">
                    <i class="fas fa-save"></i>
                    Guardar
                </button>
            </div>
        </div>
        {{ form_end(form) }}
    {% endblock %}

    {% block card_footer %}
        {% if showButton is defined and showButton == true%}
            <div class="card-footer text-body-secondary">
                <a href="{{ path('camera_index') }}" class="btn btn-primary">
                    <i class="fas fa-arrow-left"></i>
                    Listado
                </a>
            </div>
        {% endif %}
    {% endblock %}
{% endembed %}

templates/structured_cable/_form_modem.html.twig
{% embed "embeds/card.html.twig" %}
    {% block card_css_class %}mb-4{% endblock %}

    {% block card_header_css_class %}d-flex justify-content-between align-items-center{% endblock %}

    {% block card_title %}{{ title }}{% endblock %}

    {% block card_header_options %}
        <div>
            {% if showButton is defined and showButton == true%}
                <a class="btn btn-primary btn-sm active" href="{{ path('camera_index') }}">
                    <i class="fas fa-arrow-left"></i>
                    Listado
                </a>
            {% endif %}

            {% if camera is defined %}
                {{ include('structured_cable/_delete_form.html.twig', {'camera': camera}) }}
            {% endif %}
        </div>
    {% endblock %}

    {% block card_body %}
        {% form_theme form 'form/bootstrap_5_horizontal_layout_sm.html.twig' %}

        {{ form_start(form) }}
            {{ form_widget(form) }}
        <div class="row mb-3">
            <div class="col-sm-10 offset-sm-2">
                <button class="btn btn-success">
                    <i class="fas fa-save"></i>
                    Guardar
                </button>
            </div>
        </div>
        {{ form_end(form) }}
    {% endblock %}

    {% block card_footer %}
        {% if showButton is defined and showButton == true%}
            <div class="card-footer text-body-secondary">
                <a href="{{ path('camera_index') }}" class="btn btn-primary">
                    <i class="fas fa-arrow-left"></i>
                    Listado
                </a>
            </div>
        {% endif %}
    {% endblock %}
{% endembed %}

templates/structured_cable/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit StructuredCable{% endblock %}

{% block body %}
    <h1>Edit StructuredCable</h1>

    {{ include('structured_cable/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('structured_cable/_delete_form.html.twig') }}
{% endblock %}

templates/structured_cable/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}StructuredCable index{% endblock %}

{% block body %}
    <h1>StructuredCable index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>PhysicalAddress</th>
                <th>Point</th>
                <th>Path</th>
                <th>FeederCable</th>
                <th>Pair</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for structured_cable in structured_cables %}
            <tr>
                <td>{{ structured_cable.id }}</td>
                <td>{{ structured_cable.physicalAddress }}</td>
                <td>{{ structured_cable.point }}</td>
                <td>{{ structured_cable.path }}</td>
                <td>{{ structured_cable.feederCable }}</td>
                <td>{{ structured_cable.pair }}</td>
                <td>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/structured_cable/new.html.twig
{% extends 'content.html.twig' %}

{% block title %}Nuevo Cable estructurado{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8">
            <h3 class="text-dark mb-4">Crear nuevo cable estructurado</h3>
        </div>
        {{ component('Breadcrumb', {
            options: [
                {label: 'Inicio', href: path('app_home')},
                {label: 'Cable estructurado', href: ''},
                {label: 'Nuevo'},
            ],
            current: 'Nuevo'
        }) }}
    </div>

    {{ include('structured_cable/_form.html.twig', {'showButton': true, 'title': 'Crear cable estructurado'}) }}
{% endblock %}

templates/structured_cable/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}StructuredCable{% endblock %}

{% block body %}
    <h1>StructuredCable</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ structured_cable.id }}</td>
            </tr>
            <tr>
                <th>PhysicalAddress</th>
                <td>{{ structured_cable.physicalAddress }}</td>
            </tr>
            <tr>
                <th>Point</th>
                <td>{{ structured_cable.point }}</td>
            </tr>
            <tr>
                <th>Path</th>
                <td>{{ structured_cable.path }}</td>
            </tr>
            <tr>
                <th>FeederCable</th>
                <td>{{ structured_cable.feederCable }}</td>
            </tr>
            <tr>
                <th>Pair</th>
                <td>{{ structured_cable.pair }}</td>
            </tr>
        </tbody>
    </table>

    {{ include('structured_cable/_delete_form.html.twig') }}
{% endblock %}