src/Entity/Report.php
<?php

namespace App\Entity;

use App\Entity\Enums\Aim;
use App\Entity\Enums\Flaw;
use App\Entity\Enums\InterruptionReason;
use App\Entity\Enums\Priority;
use App\Entity\Enums\ReportState;
use App\Entity\Enums\ReportType;
use App\Repository\ReportRepository;
use DateTime;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ReportRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Report
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $number = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'El reporte debe de tener una especialidad.')]
    private string $specialty = 'videoproteccion';

    #[ORM\Column]
    private ?DateTimeImmutable $entryDate = null;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $closeDate = null;

    #[ORM\Column(length: 255)]
    private string $type;

    #[Assert\Choice(
        choices: [ReportType::Camera, ReportType::Server, ReportType::Msam, ReportType::Modem, ReportType::Switch],
        message: 'Seleccione un tipo de reporte válido.'
    )]
    private ReportType $enumType;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $interruptionReason = null;

    #[ORM\Column(length: 255)]
    private string $priority;

    #[Assert\Choice(
        choices: [Priority::Hight, Priority::Medium, Priority::Low],
        message: 'Seleccione una prioridad válida.'
    )]
    private Priority $enumPriority;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Valid]
    private ?Equipment $equipment = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $flaw = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $observation = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $solution = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'El reporte debe de tener una unidad.')]
    private string $unit = 'Unidad 1';

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Valid]
    private ?User $boss = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Valid]
    private ?User $managementOfficer = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    #[Assert\Valid]
    private ?User $technical = null;

    #[ORM\Column(length: 255)]
    private string $state;

    #[Assert\Choice(choices: [ReportState::Open, ReportState::Close], message: 'Seleccione un estado válido.')]
    private ReportState $enumState;

    #[ORM\Column(length: 255)]
    private string $aim;

    #[Assert\Choice(choices: [Aim::Via, Aim::Objective, Aim::Border, Aim::Confrontation, Aim::Tuition], message: 'Seleccione una función válida.')]
    private Aim $enumAim;

    #[ORM\ManyToOne]
    #[Assert\Valid]
    private ?Organ $organ = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $detail = null;

    public function __construct()
    {
//        $this->entryDate = new \DateTime();
//        $this->number = $this->entryDate->getTimestamp().'-'.$this->equipment->getShortName();
        $this->enumPriority = Priority::Hight;
        $this->enumState = ReportState::Open;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): string
    {
        return $this->number;
    }

    public function setNumber(string $number): static
    {
        $this->number = $number;

        return $this;
    }

    public function getSpecialty(): string
    {
        return str_replace('_', ' ', $this->specialty);
    }

    /*public function setSpecialty(string $specialty): static
    {
        $this->specialty = $specialty;

        return $this;
    }*/

    public function getEntryDate(): ?DateTimeImmutable
    {
        return $this->entryDate;
    }

    public function setEntryDate(DateTimeImmutable $entryDate): static
    {
        $this->entryDate = $entryDate;

        return $this;
    }

    public function getCloseDate(): ?DateTimeImmutable
    {
        return $this->closeDate;
    }

    public function setCloseDate(?DateTimeImmutable $closeDate): static
    {
        $this->closeDate = $closeDate;

        return $this;
    }

    public function getType(): ReportType
    {
        return $this->enumType;
    }

    public function setType(ReportType $type): static
    {
        $this->enumType = $type;

        return $this;
    }

    public function getInterruptionReason(): ?string
    {
        return $this->interruptionReason;
    }

    public function setInterruptionReason(InterruptionReason|string|null $interruptionReason): static
    {
        /*if(is_string($interruptionReason)){
            $this->interruptionReason = $interruptionReason;
        }else{
            $this->interruptionReason = $interruptionReason->value;
        }*/

        $this->interruptionReason = (is_string($interruptionReason)) ? $interruptionReason : $interruptionReason->value;

        return $this;
    }

    public function getPriority(): Priority
    {
        return $this->enumPriority;
    }

    public function setPriority(Priority $priority): static
    {
        $this->enumPriority = $priority;

        return $this;
    }

    public function getEquipment(): ?Equipment
    {
        return $this->equipment;
    }

    public function setEquipment(Equipment $equipment): static
    {
        $this->equipment = $equipment;

        return $this;
    }

    public function getFlaw(): ?string
    {
        return $this->flaw;
    }

    public function setFlaw(Flaw|string|null $flaw): static
    {
        /*if(is_string($flaw)){
            $this->flaw = $flaw;
        }else{
            $this->flaw = $flaw->value;
        }*/
        $this->flaw = (is_string($flaw)) ? $flaw : $flaw->value;

        return $this;
    }

    public function getObservation(): ?string
    {
        return $this->observation;
    }

    public function setObservation(?string $observation): static
    {
        $this->observation = $observation;

        return $this;
    }

    public function getSolution(): ?string
    {
        return $this->solution;
    }

    public function setSolution(?string $solution): static
    {
        $this->solution = $solution;

        return $this;
    }

    public function getUnit(): string
    {
        return $this->unit;
    }

    public function setUnit(string $unit): static
    {
        $this->unit = $unit;

        return $this;
    }

    public function getBoss(): ?User
    {
        return $this->boss;
    }

    public function setBoss(?User $boss): static
    {
        $this->boss = $boss;

        return $this;
    }

    public function getManagementOfficer(): ?User
    {
        return $this->managementOfficer;
    }

    public function setManagementOfficer(?User $managementOfficer): static
    {
        $this->managementOfficer = $managementOfficer;

        return $this;
    }

    public function getState(): ReportState
    {
        return $this->enumState;
    }

    public function setState(ReportState $state): static
    {
        $this->enumState = $state;

        return $this;
    }

    public function getAim(): Aim
    {
        return $this->enumAim;
    }

    public function setAim(Aim $aim): static
    {
        $this->enumAim = $aim;

        return $this;
    }

    public function getOrgan(): ?Organ
    {
        return $this->organ;
    }

    public function setOrgan(?Organ $organ): static
    {
        $this->organ = $organ;

        return $this;
    }

    public function getPhysicalAddress(): string
    {
        return $this->getEquipment()->getPhysicalAddress();
    }

    public function getMunicipality(): Municipality
    {
        return $this->getEquipment()->getMunicipality();
    }

    #[ORM\PrePersist]
    public function beforeSave(): void
    {
        $this->entryDate = new DateTimeImmutable();
        $this->number = $this->entryDate->getTimestamp().'-'.$this->equipment->getShortName();
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function onSave(): void
    {
        $this->type = $this->getType()->value;
        $this->priority = $this->getPriority()->value;
        $this->state = $this->getState()->value;
        $this->aim = $this->getAim()->value;
    }

    #[ORM\PostLoad]
    public function onLoad(): void
    {
        $this->setType(ReportType::from($this->type));
        $this->setPriority(Priority::from($this->priority));
        $this->setState(ReportState::from($this->state));
        $this->setAim(Aim::from($this->aim));
    }

    public function close(): void
    {
        if($this->getSolution()){
            $this->closeDate = new DateTimeImmutable('now');
            $this->setState(ReportState::Close);
        }
    }

    public function isOpen(): bool
    {
        return $this->enumState->value === ReportState::Open->value;
    }

    public function getTechnical(): ?User
    {
        return $this->technical;
    }

    public function setTechnical(?User $technical): static
    {
        $this->technical = $technical;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

}

templates/components/live/connection_list/table/_table_direct.html.twig
{% embed "embeds/async_table.html.twig" %}
    {% from 'macros/report.html.twig' import report %}

    {% block table_head %}
        <tr>
            <th>Switch</th>
            <th>Puerto</th>
            <th>Cámara</th>
            <th>Provincia</th>
            <th>Municipio</th>
            <th></th>
        </tr>
    {% endblock %}

    {% block table_body %}
        {% for camera in paginator.getData() %}
            <tr>
                <td>
                    <a href="{{ path('commutator_state') }}" class="text-decoration-none"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.port.commutator.id }}"
                            {% if camera.port.commutator.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.port.commutator.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {{ camera.port.commutator.ip }}
                            </span>
                        {% if camera.port.commutator.gateway %}({{ camera.port.commutator.gateway }}){% endif%}
                        {% if camera.port.commutator.multicast %}[{{ camera.port.commutator.multicast }}]{% endif %}
                    </a>
                    {{ report(camera.port.commutator.state, camera.port.commutator.id, 5, 'Reportar switch') }}
                </td>
                <td>
                    <a href="{{ path('port_state') }}"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.port.id }}"
                            {% if camera.port.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.port.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {{ camera.port.number }}
                            </span>
                    </a>
                </td>
                <td>
                    <a href="{{ path('camera_state') }}" class="text-decoration-none"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.id }}"
                            {% if camera.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {{ camera.ip }}
                            </span>
                    </a>
                    {{ report(camera.state, camera.id, 1, 'Reportar cámara') }}
                </td>
                <td>{{ camera.municipality.province.name }}</td>
                <td>{{ camera.municipality.name }}</td>
                <td>
                    <button title="Detalle de conexión"
                            type="button"
                            class="btn btn-primary btn-sm"
                            aria-current="page"
                            data-action="live#action"
                            data-action-name="prevent|detail(entityId={{ camera.id }})"
                    >
                        <i class="fas fa-eye"></i>
                    </button>

                    {% if is_granted('ROLE_BOSS') %}
                        <button title="Eliminar conexión"
                                type="button"
                                class="btn btn-primary btn-sm"
                                aria-current="page"
                                data-action="connection-list-table#disconnect"
                                data-connection-list-table-camera-param="{{ camera.id }}"
                        >
                            <i class="fas fa-plug"></i>
                        </button>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">
                    No se encontraron registros
                </td>
            </tr>
        {% endfor %}
    {% endblock %}
{% endembed %}

templates/components/live/connection_list/table/_table_full.html.twig
{% embed "embeds/async_table.html.twig" %}
    {% from 'macros/report.html.twig' import report %}

    {% block table_head %}
        <tr>
            <th>Switch</th>
            <th>Puerto</th>
            <th>Msam</th>
            <th>Slot</th>
            <th>Card</th>
            <th>Puerto</th>
            <th>Modem</th>
            <th>Cámara</th>
            <th>Provincia</th>
            <th>Municipio</th>
            <th></th>
        </tr>
    {% endblock %}

    {% block table_body %}
        {% for camera in paginator.getData() %}
            <tr>
                <td>
                    <a href="{{ path('commutator_state') }}" class="text-decoration-none"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.modem.port.card.msam.port.commutator.id }}"
                            {% if camera.modem.port.card.msam.port.commutator.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.modem.port.card.msam.port.commutator.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {{ camera.modem.port.card.msam.port.commutator.ip }}
                            </span>
                        {% if camera.modem.port.card.msam.port.commutator.gateway %}({{ camera.modem.port.card.msam.port.commutator.gateway }}){% endif%}
                        {% if camera.modem.port.card.msam.port.commutator.multicast %}[{{ camera.modem.port.card.msam.port.commutator.multicast }}]{% endif %}
                    </a>
                    {{ report(camera.modem.port.card.msam.port.commutator.state, camera.modem.port.card.msam.port.commutator.id, 5, 'Reportar switch') }}
                </td>
                <td>
                    <a href="{{ path('port_state') }}"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.modem.port.card.msam.port.id }}"
                            {% if camera.modem.port.card.msam.port.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.modem.port.card.msam.port.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {{ camera.modem.port.card.msam.port.number }}
                            </span>
                    </a>
                </td>
                <td>
                    <a href="{{ path('msam_state') }}" class="text-decoration-none"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.modem.port.card.msam.id }}"
                            {% if camera.modem.port.card.msam.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.modem.port.card.msam.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {% if camera.modem.port.card.msam.ip %}{{ camera.modem.port.card.msam.ip }}{% else %}Sin IP{% endif %}
                            </span>
                    </a>
                    {{ report(camera.modem.port.card.msam.state, camera.modem.port.card.msam.id, 3, 'Reportar msam') }}
                </td>
                <td>{{ camera.modem.port.card.slot }}</td>
                <td>{{ camera.modem.port.card.name }}</td>
                <td>
                    <a href="{{ path('port_state') }}"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.modem.port.id }}"
                            {% if camera.modem.port.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.modem.port.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {{ camera.modem.port.number }}
                            </span>
                    </a>
                </td>
                <td>
                    <a href="{{ path('modem_state') }}" class="text-decoration-none"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.modem.id }}"
                            {% if camera.modem.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.modem.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {% if camera.modem.ip %}{{ camera.modem.ip }}{% else %}Sin IP{% endif %}
                            </span>
                    </a>
                    {{ report(camera.modem.state, camera.modem.id, 2, 'Reportar modem') }}
                </td>
                <td>
                    <a href="{{ path('camera_state') }}" class="text-decoration-none"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.id }}"
                            {% if camera.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {{ camera.ip }}
                            </span>
                    </a>
                    {{ report(camera.state, camera.id, 1, 'Reportar cámara') }}
                </td>
                <td>{{ camera.municipality.province.name }}</td>
                <td>{{ camera.municipality.name }}</td>
                <td>
                    <button title="Detalle de conexión"
                            type="button"
                            class="btn btn-primary btn-sm"
                            aria-current="page"
                            data-action="live#action"
                            data-action-name="prevent|detail(entityId={{ camera.id }})"
                    >
                        <i class="fas fa-eye"></i>
                    </button>
                    {% if is_granted('ROLE_BOSS') %}
                        <button title="Eliminar conexión"
                                type="button"
                                class="btn btn-primary btn-sm"
                                aria-current="page"
                                data-action="connection-list-table#disconnect"
                                data-connection-list-table-camera-param="{{ camera.id }}"
                        >
                            <i class="fas fa-plug"></i>
                        </button>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">
                    No se encontraron registros
                </td>
            </tr>
        {% endfor %}
    {% endblock %}
{% endembed %}

templates/components/live/connection_list/table/_table_simple.html.twig
{% embed "embeds/async_table.html.twig" %}
    {% from 'macros/report.html.twig' import report %}

    {% block table_head %}
        <tr>
            <th>Switch</th>
            <th>Puerto</th>
            <th>Modem</th>
            <th>Cámara</th>
            <th>Provincia</th>
            <th>Municipio</th>
            <th></th>
        </tr>
    {% endblock %}

    {% block table_body %}
        {% for camera in paginator.getData() %}
            <tr>
                <td>
                    <a href="{{ path('commutator_state') }}" class="text-decoration-none"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.modem.port.commutator.id }}"
                            {% if camera.modem.port.commutator.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.modem.port.commutator.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {{ camera.modem.port.commutator.ip }}
                            </span>
                        {% if camera.modem.port.commutator.gateway %}({{ camera.modem.port.commutator.gateway }}){% endif%}
                        {% if camera.modem.port.commutator.multicast %}[{{ camera.modem.port.commutator.multicast }}]{% endif %}
                    </a>
                    {{ report(camera.modem.port.commutator.state, camera.modem.port.commutator.id, 5, 'Reportar switch') }}
                </td>
                <td>
                    <a href="{{ path('port_state') }}"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.modem.port.id }}"
                            {% if camera.modem.port.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.modem.port.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {{ camera.modem.port.number }}
                            </span>
                    </a>
                </td>
                <td>
                    <a href="{{ path('modem_state') }}" class="text-decoration-none"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.modem.id }}"
                            {% if camera.modem.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.modem.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {% if camera.modem.ip %}{{ camera.modem.ip }}{% else %}Sin IP{% endif %}
                            </span>
                    </a>
                    {{ report(camera.modem.state, camera.modem.id, 2, 'Reportar modem') }}
                </td>
                <td>
                    <a href="{{ path('camera_state') }}" class="text-decoration-none"
                       data-action="page#state:prevent"
                       data-page-id-param="{{ camera.id }}"
                            {% if camera.state %}
                                data-page-state-param="0"
                            {% else %}
                                data-page-state-param="1"
                            {% endif %}
                    >
                            <span
                                    class="badge {% if camera.state %}text-bg-success{% else %}text-bg-danger{% endif %}"
                            >
                                {{ camera.ip }}
                            </span>
                    </a>
                    {{ report(camera.state, camera.id, 1, 'Reportar cámara') }}
                </td>
                <td>{{ camera.municipality.province.name }}</td>
                <td>{{ camera.municipality.name }}</td>
                <td>
                    <button title="Detalle de conexión"
                            type="button"
                            class="btn btn-primary btn-sm"
                            aria-current="page"
                            data-action="live#action"
                            data-action-name="prevent|detail(entityId={{ camera.id }})"
                    >
                        <i class="fas fa-eye"></i>
                    </button>
                    {% if is_granted('ROLE_BOSS') %}
                        <button title="Eliminar conexión"
                                type="button"
                                class="btn btn-primary btn-sm"
                                aria-current="page"
                                data-action="connection-list-table#disconnect"
                                data-connection-list-table-camera-param="{{ camera.id }}"
                        >
                            <i class="fas fa-plug"></i>
                        </button>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">
                    No se encontraron registros
                </td>
            </tr>
        {% endfor %}
    {% endblock %}
{% endembed %}